name: Publish Blog Posts
on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish to Hashnode
        uses: prettyirrelevant/hashnode-posts-publisher@v0.1.3
        with:
          posts-directory: posts # ← 実在ディレクトリ名
          supported-formats: md,html
          access-token: ${{ secrets.HASHNODE_TOKEN }}
          publication-id: ${{ secrets.HASHNODE_PUBLICATION_ID }}
