name: Publish Blog Posts
on:
  push:
    branches: ["main"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish to Hashnode
        uses: vriteio/hashnode-publisher@v0.1.2
        with:
          token: ${{ secrets.HASHNODE_TOKEN }}
          publicationId: ${{ secrets.HASHNODE_PUBLICATION_ID }}
          contentPath: posts
