name: Publish Blog Posts
on:
  push:
    branches: ["main"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish to Hashnode
        uses: prettyirrelevant/hashnode-posts-publisher@v0.1.3
        with:
          posts-directory: posts
          supported-formats: md
          access-token: ${{ secrets.HASHNODE_TOKEN }}
          publication-id: ${{ secrets.HASHNODE_PUBLICATION_ID }}
